export const authStyles = {
  wrapper: 'w-full min-h-full px-5',
  container: 'w-full flex flex-col items-center',
  form: 'w-full flex flex-col items-center gap-6',
  iconWrapper: 'mt-4 mb-4',
  icon: 'w-[80px] h-[80px]',
  titleWrapper: 'mb-4',
  tabContainer: 'w-full flex border-b border-stroke mb-6',
  tab: 'flex-1 py-4 text-center',
  activeTab: 'border-b-2 border-primary text-primary font-medium',
  inactiveTab: 'text-font2',
  resultContainer: 'w-full flex flex-col items-center gap-4',
  resultBox: 'w-full bg-white p-6 rounded-lg border border-stroke space-y-4',
  buttonContainer: 'w-full space-y-4 mt-6',
};
